<pre><?php

require_once('RSSLinkFilters.php');


function loadRSS($link) {
    $useragent = "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.700.3 Safari/534.24";
    
        $ch = curl_init();
        
            curl_setopt($ch, CURLOPT_URL, $link);
                curl_setopt($ch, CURLOPT_HEADER, 0);
                    curl_setopt($ch, CURLOPT_NOBODY, 0);
                        curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
                            curl_setopt($ch, CURLOPT_FOLLOWLOCATION , true);
                                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                    
                                        $result = curl_exec($ch);
                                            
                                                curl_close($ch);
                                                
                                                    return $result;
                                                    }
                                                    
                                                    
                                                    function getRealLink($link) {
                                                        $useragent = "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.700.3 Safari/534.24";
                                                        
                                                            $ch = curl_init();
                                                            
                                                                curl_setopt($ch, CURLOPT_URL, $link);
                                                                    curl_setopt($ch, CURLOPT_HEADER, 1);
                                                                        curl_setopt($ch, CURLOPT_NOBODY, 1);
                                                                            curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
                                                                                curl_setopt($ch, CURLOPT_FOLLOWLOCATION , true);
                                                                                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                                                                        
                                                                                            curl_exec($ch);
                                                                                                
                                                                                                    $header    = curl_getinfo( $ch ); 
                                                                                                        $real_link = $header['url'];
                                                                                                        
                                                                                                            curl_close($ch);
                                                                                                                
                                                                                                                    
                                                                                                                        
                                                                                                                            return $real_link;
                                                                                                                            }
                                                                                                                            
                                                                                                                            
                                                                                                                            function tt($url, $cutQS = false) {
                                                                                                                                $parts = parse_url($url);
                                                                                                                                    $new_url = '';
                                                                                                                                        
                                                                                                                                            if (array_key_exists('scheme', $parts)) {
                                                                                                                                                     $new_url .= $parts['scheme'] . '://';
                                                                                                                                                         }
                                                                                                                                                             if (array_key_exists('user', $parts)) {
                                                                                                                                                                      $new_url .= $parts['user'];
                                                                                                                                                                          
                                                                                                                                                                                  if (array_key_exists('pass', $parts)) {
                                                                                                                                                                                              $new_url .= ':' . $parts['pass'];
                                                                                                                                                                                                      }
                                                                                                                                                                                                              
                                                                                                                                                                                                                       $new_url .= '@';
                                                                                                                                                                                                                           }
                                                                                                                                                                                                                               if (array_key_exists('host', $parts)) {
                                                                                                                                                                                                                                        $new_url .= $parts['host'];
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                if (array_key_exists('port', $parts)) {
                                                                                                                                                                                                                                                         $new_url .= ':' . $parts['port'];
                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                 if (array_key_exists('path', $parts)) {
                                                                                                                                                                                                                                                                          $new_url .= $parts['path'];
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                  if (!$cutQS && array_key_exists('query', $parts)) {
                                                                                                                                                                                                                                                                                           $new_url .= '?' . $parts['query'];
                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                   if (array_key_exists('fragment', $parts)) {
                                                                                                                                                                                                                                                                                                            $new_url .= '#' . $parts['fragment'];
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    return $new_url;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    error_reporting(E_ALL);
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    $link = $_SERVER["QUERY_STRING"];
                                                                                                                                                                                                                                                                                                                    $xml = loadRSS($link); 
                                                                                                                                                                                                                                                                                                                    $dom = new DOMDocument();
                                                                                                                                                                                                                                                                                                                    $dom->preserveWhiteSpace = false;
                                                                                                                                                                                                                                                                                                                    $dom->LoadXml($xml);
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    $filterName = 'trench';
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    $xpath    = new DOMXPath($dom);
                                                                                                                                                                                                                                                                                                                    $nodeList = $xpath->query("//item");
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                    for( $i = 0; $i < $nodeList->length; $i++) {
                                                                                                                                                                                                                                                                                                                        $item = $nodeList->item($i);
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                $titleList = $xpath->query("title", $item);
                                                                                                                                                                                                                                                                                                                                    $linkList  = $xpath->query("link",  $item);
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            if ($titleList->length > 0 && $linkList->length > 0) {
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                        echo $titleList->item(0)->nodeValue, PHP_EOL;
                                                                                                                                                                                                                                                                                                                                                                echo $linkList->item(0)->nodeValue, PHP_EOL;
                                                                                                                                                                                                                                                                                                                                                                        echo $lk = getRealLink($linkList->item(0)->nodeValue), PHP_EOL;
                                                                                                                                                                                                                                                                                                                                                                                echo tt($lk, true), PHP_EOL;
                                                                                                                                                                                                                                                                                                                                                                                        echo PHP_EOL, PHP_EOL;
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                        }