<div id="content_text"><br />
<div id="header" align="left">Мини-игры</div>
<img src="/images/icons/minigame.png" id="label"/><br />
<p align="left">
Алидерия – большая онлайн-игра с огромной кучей игровых вариаций и возможностей. Наш мир постоянно дорабатывается, создается что-то новое, при чем чаще всего это новое предлагаете ввести Вы. Вы, игроки, делаете Алидерию нашими руками.<br /><br />
В игре не должно быть скучно, никогда. Это закон. Иначе это неинтересная игра. Но бывают немного рутинные игровые моменты (как-то добыча или крафт-создание вещей), но и здесь мы спешим Вам на помощь.<br /><br />
В игре существует такое понятие как «мини-игры» - это маленькие игры, в которые можно играть с другими игроками, не нарушая и не отвлекаясь особо от основного игрового процесса. Найти их можно по кнопке «Мини-Игры» между кнопками «Помощь» и «Форум» (над списком игроков в чате). Посе того, как Вы кликнете, Вашему вниманию откроется некий список игр. Вам стоит лишь выбрать во что играть и подобрать себе напарника.<br /><br />
На самом деле мини-игр в Алидерии масса, ни в одном другом проекте их нету так много, но большинство из них в квестах, дабы разнообразить их прохождение. ДА и нам кажется, что это интереснее, чем просто бегать носить товары с точки А в точку В. <br /><br />
Список игр, который Вы видите, это далеко не полный список. Как уже говорилось ранее, мы постоянно дорабатываем игровой мир и время от времени будут появляться новые мини-игры. Заглядывайте в них почаще.
<br /><br />
<table><tbody><form>
<tr><td><input value="Карты" ONCLICK="location.href='/help.php?id=19010'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input value="Покер" ONCLICK="location.href='/help.php?id=19030'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input style='display:none' value="" ONCLICK="location.href='/help.php?id=19050'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input style='display:none' value="" ONCLICK="location.href='/help.php?id=19070'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input style='display:none' value="" ONCLICK="location.href='/help.php?id=19090'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td></tr>
<tr><td><input value="Шахматы" ONCLICK="location.href='/help.php?id=19020'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input value="5 в Ряд" ONCLICK="location.href='/help.php?id=19040'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input style='display:none' value="" ONCLICK="location.href='/help.php?id=19060'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input style='display:none' value="" ONCLICK="location.href='/help.php?id=19080'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td><td><input style='display:none' value="" ONCLICK="location.href='/help.php?id=19100'" type="button" style="width:126px; height:28px; background:url(/images/buttom.png); border: 0;"></td></tr>
</tbody></table>
</p>
</div>
